### ISSUE TITLE
What is the design target for this project?

### ISSUE THREAD

**Issue by anticpp** [uber-go/config#67]
I have been following this project when it's on `https://github.com/uber-go/fx/config`.

Comparing to traditional way to deal with configurations from command line,file,environment or some key-value storage(consul/etcd). I think is an excellent idea to unify these with `provider`. 
So , I am expecting for completion for this.

But, I notice that there are big differences from the earlier versions, I am confused. Like.

- ChangeCallback removed from provider
- Commandline provider is removed
- ...balabla

I believe there are more inside-team disscussioins, that guiding this way.

Can some explain what is the design target for the future?

**Comment by breerly** [comment]
Hi @anticpp, you're right - we made breaking changes on the way to v1.0 in order to get this library down to the bare minimum needed to build Fx modules.

Now `v1.0` has been released, we are committing to keeping the API backwards compatible for v1.x releases. This can be thought of as a Long Term Stable, meaning v1.x will be maintained on the order of years, not months. New features will likely be added, but non will be removed.

To see how these version mechanics work, read up on http://semver.org/.
